interface BottomLineProps {
  items?: string[];
  itemsHtml?: string[];
}

// itemsHtml is generated by marked.parseInline() from first-party MDX in src/content/guides
// with auto-injected affiliate-link markdown — same trust boundary as pick.bodyHtml.
export default function BottomLine({ items, itemsHtml }: BottomLineProps) {
  const list = itemsHtml?.length ? itemsHtml : items;
  if (!list?.length) return null;
  const isHtml = !!itemsHtml?.length;

  return (
    <section id="bottom-line" className="mb-16 scroll-mt-24">
      <h2
        className="font-serif text-2xl md:text-3xl font-bold mb-6"
        style={{ color: "var(--color-navy)" }}
      >
        Bottom Line
      </h2>
      <div className="space-y-4">
        {list.map((para, i) =>
          isHtml ? (
            <p
              key={i}
              className="text-base leading-relaxed pl-4 border-l-2 affiliate-prose"
              style={{
                color: "var(--color-text)",
                borderLeftColor: "var(--color-teal)",
              }}
              dangerouslySetInnerHTML={{ __html: para }}
            />
          ) : (
            <p
              key={i}
              className="text-base leading-relaxed pl-4 border-l-2"
              style={{
                color: "var(--color-text)",
                borderLeftColor: "var(--color-teal)",
              }}
            >
              {para}
            </p>
          ),
        )}
      </div>
    </section>
  );
}
