#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from '../lib/content-audit.mjs';

const reportsDir = path.join(ROOT, 'docs/refresh/reports');
fs.mkdirSync(reportsDir, { recursive: true });

const checks = [
  {
    name: 'Guide sitemap pattern has route',
    urlPattern: '/guides/${guide.slug}',
    routeFile: 'src/app/guides/[slug]/page.tsx',
  },
  {
    name: 'Category review sitemap pattern has route',
    urlPattern: '/reviews/${cat.slug}',
    routeFile: 'src/app/reviews/[category]/page.tsx',
  },
  {
    name: 'Product review sitemap pattern has route',
    urlPattern: '/reviews/${product.category}/${product.slug}',
    routeFile: 'src/app/reviews/[category]/[slug]/page.tsx',
  },
];

const rows = checks.map((check) => ({
  ...check,
  exists: fs.existsSync(path.join(ROOT, check.routeFile)),
}));
const missing = rows.filter((row) => !row.exists);
const markdown = `# Sitemap Route Pattern Audit\n\nGenerated by \`node scripts/refresh/audit-routes.mjs\`.\n\n## Summary\n\n- Route patterns checked: ${rows.length}\n- Missing route files: ${missing.length}\n\n## Checks\n\n${rows.map((row) => `- ${row.exists ? 'PASS' : 'FAIL'} — ${row.name}: \`${row.urlPattern}\` -> \`${row.routeFile}\``).join('\n')}\n`;

fs.writeFileSync(path.join(reportsDir, 'sitemap-route-audit.json'), `${JSON.stringify({ routePatternCount: rows.length, missingCount: missing.length, rows }, null, 2)}\n`);
fs.writeFileSync(path.join(reportsDir, 'sitemap-route-audit.md'), markdown);
console.log(`Wrote docs/refresh/reports/sitemap-route-audit.md and sitemap-route-audit.json`);
console.log(`Missing route files: ${missing.length}`);
if (missing.length) process.exitCode = 1;
